name: maddpg-baseline-lane-controller

agent:
  state:
    wrapper:
      name: Simple
    features:
      goal_relative_pos: True
      distance_to_center: True
      speed: True
      steering: True
      heading_errors: [20, continuous]
      neighbor: 8
  action:
    type: 1   # 0 for continuous, 1 for discrete

interface:
  max_episode_steps: 1000
  neighborhood_vehicles:
    radius: 50
  waypoints:
    lookahead: 50   # larger than size of heading errors

policy:
  framework: rllib
  trainer:
    path: benchmark.agents.sac.sac_agent
    name: SacdAgent

run:
  checkpoint_freq: 40
  checkpoint_at_end: True
  max_failures: 1000
  resume: False
  export_formats: [model, checkpoint]
  stop:
    time_total_s: 14400
  config:
    num_steps: 300000
    batch_size: 64
    lr: 0.0003
    memory_size: 2000
    gamma: 0.99
    multi_step: 1
    target_entropy_ratio: 0.98
    start_steps: 1000
    update_interval: 4
    target_update_interval: 8000
    use_per: False
    dueling_net: False
    num_eval_steps: 100000
    max_episode_steps: 27000
    log_interval: 10
    eval_interval: 5000
